/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "sprintf.check" instead.
 */

#include <check.h>

#include "s21_string.h"

START_TEST(sprintf)
{

char str1[BUFF_SIZE];
char str2[BUFF_SIZE];
char *format = "This is a simple value %d";
int val = 69;
ck_assert_int_eq(s21_sprintf(str1, format, val),
                     sprintf(str2, format, val));

ck_assert_str_eq(str1, str2);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, sprintf);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
