/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "strchr.check" instead.
 */

#include <check.h>


#include "s21_string.h"


START_TEST(strchr1)
{
char str19[100] = "12345", str20[100] = "ghjtfdW", str21[100] = "-12345%s",
     str22[100] = "", str23[100] = "000/0";
ck_assert_ptr_eq(s21_strchr(str19, '*'), strchr(str19, '*'));
ck_assert_ptr_eq(s21_strchr(str20, 'j'), strchr(str20, 'j'));
ck_assert_ptr_eq(s21_strchr(str21, '%' ), strchr(str21, '%'));
ck_assert_ptr_eq(s21_strchr(str22, 'G' ), strchr(str22, 'G' ));
ck_assert_ptr_eq(s21_strchr(str23, '0' ), strchr(str23, '0'));
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, strchr1);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
