/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "strcat.check" instead.
 */

#include <check.h>

#include "s21_string.h"

START_TEST(strcat1)
{
char str6[100] = "12345", str7[100] = "6789", str8[100] = "-12345%s",
     str9[100] = "", str10[100] = "000/000";
char str12[100] = "45rtvb", str13[100] = "0000\n";
ck_assert_str_eq(s21_strcat(str6, str12), strcat(str6, str12));
ck_assert_str_eq(s21_strcat(str7, str12), strcat(str7, str12));
ck_assert_str_eq(s21_strcat(str8, str13), strcat(str8, str13));
ck_assert_str_eq(s21_strcat(str9, str13), strcat(str9, str13));
ck_assert_str_eq(s21_strcat(str10, str12), strcat(str10, str12));
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, strcat1);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
