/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "s21_string_test.check" instead.
 */

#include <check.h>

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "s21_string.h"

START_TEST(memchr_test)
{
char str24[100] = "", str25[100] = "string", str26[100] = "Atring", str27[100] = "StringA",
str28[100] = "Str55333222ingA", str29[100] = "00000000";
ck_assert_ptr_eq(s21_memchr(str24, '\0', 0), memchr(str24, '\0', 0));
ck_assert_ptr_eq(s21_memchr(str25, '\0', 7), memchr(str25, '\0', 7));
ck_assert_ptr_eq(s21_memchr(str26, 'A', 6), memchr(str26, 'A', 6));
ck_assert_ptr_eq(s21_memchr(str27, 'A', 7), memchr(str27, 'A', 7));
ck_assert_ptr_eq(s21_memchr(str28, '3', 15), memchr(str28, '3', 15));
ck_assert_ptr_eq(s21_memchr(str29, '-', 9), memchr(str29, '-', 9));

}
END_TEST

START_TEST(memcmp_test)
{
char str31[100] = "aboba", str32[100] = "aboba", str33[100] = "Aboba",
str34[100] = "1", str35[100] = "1",  str36[100] = "1234",  str37[100] = "13",
 str38[100] = "111111111111111111112312312312312312434524563567adsfe 4rafa ewfseASDASD",
 str39[100] = "111111111111111111112312312312312312434524563567adsfe 4rafa ewfseASDASd";
ck_assert_int_eq(s21_memcmp(str31, str32, 0), memcmp(str31, str32, 0));
ck_assert_int_eq(s21_memcmp(str31, str32, 3), memcmp(str31, str32, 3));
ck_assert_int_eq(s21_memcmp(str31, str33, 1), memcmp(str31, str33, 1));
ck_assert_int_eq(s21_memcmp(str34, str35, 0), memcmp(str34, str35, 0));
ck_assert_int_eq(s21_memcmp(str34, str36, 1), memcmp(str34, str36, 1));
ck_assert_int_eq(s21_memcmp(str36, str36, 2), memcmp(str36, str36, 2));
ck_assert_int_eq(s21_memcmp(str36, str37, 2), memcmp(str36, str37, 2));
ck_assert_int_eq(s21_memcmp(str38, str38, 71), memcmp(str38, str38, 71));
ck_assert_int_eq(s21_memcmp(str38, str39, 71), memcmp(str38, str39, 71));

}
END_TEST

START_TEST(memcpy_test)
{
char str40[100] = "i hate memcmp", str41[100] = "aboba", str42[100] = "",
 str43[100] = "I hate memcmp",str44[100] = "123",
str45[100] = "aposkd AOSIjFasodijpaoisdjf poisdjfg";
char dest[100] = {0};
ck_assert_str_eq(s21_memcpy(str40, dest, 12), memcpy(str40, dest, 12));
ck_assert_str_eq(s21_memcpy(str41, dest, 0), memcpy(str41, dest, 0));
ck_assert_str_eq(s21_memcpy(str42, dest, 0), memcpy(str42, dest, 0));
ck_assert_str_eq(s21_memcpy(str43, dest, 1), memcpy(str43, dest, 1));
ck_assert_str_eq(s21_memcpy(str44, dest, 3), memcpy(str44, dest, 2));
ck_assert_str_eq(s21_memcpy(str45, dest, 28), memcpy(str45, dest, 28));

}
END_TEST

START_TEST(memmove1)
{
char str46[100] = "i love memcmp",  str47[100] = "aboba", str48[100] = "",
 str49[100] = "I love memcmp",  str50[100] = "123",
str51[100] = "aposkd AOSIjFasodijpaoisdjf poisdjfg";
char dest[100] = "0000000000000000";
ck_assert_str_eq(s21_memmove(str46, dest, 12), memmove(str46, dest, 12));
ck_assert_str_eq(s21_memmove(str47, dest, 0), memmove(str47, dest, 0));
ck_assert_str_eq(s21_memmove(str48, dest, 0), memmove(str48, dest, 0));
ck_assert_str_eq(s21_memmove(str49, dest, 1), memmove(str49, dest, 1));
ck_assert_str_eq(s21_memmove(str50, dest, 3), memmove(str50, dest, 2));
ck_assert_str_eq(s21_memmove(str51, dest, 28), memmove(str51, dest, 28));

}
END_TEST

START_TEST(memset_test)
{
char str1[100] = "123456789";
char str2[100] = "Nice";
char str3[100] = "000000";
char str4[100] = "-1-2-3-4-5";
char str5[100] = " ";
int c = '1';
ck_assert_str_eq(s21_memset(str1, c, 5),memset(str1, c, 5));
ck_assert_str_eq(s21_memset(str2, c, 2),memset(str2, c, 2));
ck_assert_str_eq(s21_memset(str3, c, 10),memset(str3, c, 10));
ck_assert_str_eq(s21_memset(str4, c, 0),memset(str4, c, 0));
ck_assert_str_eq(s21_memset(str5, c, 1),memset(str5, c, 1));

}
END_TEST

START_TEST(strcat_test)
{
char str6[100] = "12345", str7[100] = "6789", str8[100] = "-12345%s",
     str9[100] = "", str10[100] = "000/000";
char str12[100] = "45rtvb", str13[100] = "0000\n";
ck_assert_str_eq(s21_strcat(str6, str12), strcat(str6, str12));
ck_assert_str_eq(s21_strcat(str7, str12), strcat(str7, str12));
ck_assert_str_eq(s21_strcat(str8, str13), strcat(str8, str13));
ck_assert_str_eq(s21_strcat(str9, str13), strcat(str9, str13));
ck_assert_str_eq(s21_strcat(str10, str12), strcat(str10, str12));

}
END_TEST

START_TEST(strncat_test)
{
char str11[100] = "12345", str12[100] = "6789", str13[100] = "-12345%s",
     str14[100] = "", str15[100] = "000/0";
char str16[100] = "", str17[100] = "45rtvb", str18[100] = "0000\n";
ck_assert_str_eq(s21_strncat(str11, str16, 2), strncat(str11, str16, 2));
ck_assert_str_eq(s21_strncat(str12, str17, 0), strncat(str12, str17, 0));
ck_assert_str_eq(s21_strncat(str13, str18, 10), strncat(str13, str18, 10));
ck_assert_str_eq(s21_strncat(str14, str16, 5), strncat(str14, str16, 5));
ck_assert_str_eq(s21_strncat(str15, str17, 1), strncat(str15, str17, 1));

}
END_TEST

START_TEST(strchr_test)
{
char str19[100] = "12345", str20[100] = "ghjtfdW", str21[100] = "-12345%s",
     str22[100] = "", str23[100] = "000/0";
ck_assert_ptr_eq(s21_strchr(str19, '3'), strchr(str19, '3'));
ck_assert_ptr_eq(s21_strchr(str20, 'j'), strchr(str20, 'j'));
ck_assert_ptr_eq(s21_strchr(str21, '%' ), strchr(str21, '%'));
ck_assert_ptr_eq(s21_strchr(str22, 'G' ), strchr(str22, 'G' ));
ck_assert_ptr_eq(s21_strchr(str23, '0' ), strchr(str23, '0'));

}
END_TEST

START_TEST(s21_strcmp_test)
{
char s1[20] = "Hello world\0";
char s3[20] = "a\n\0";
char s4[20] = " \n\0";
char s5[6] = " \0";
char s6[4] = "\n\0";
char s7[2] = "\0";
char s8[4] = "aaa";
char s9[2] = "";
char s10[20] = "Hello world\0";

ck_assert_int_eq(s21_strcmp(s4, s5), strcmp(s4, s5));
ck_assert_int_eq(s21_strcmp(s5, s7), strcmp(s5, s7));
ck_assert_int_eq(s21_strcmp(s3, s4), strcmp(s3, s4));
ck_assert_int_eq(s21_strcmp(s6, s7), strcmp(s6, s7));
ck_assert_int_eq(s21_strcmp(s8, s9), strcmp(s8, s9));
ck_assert_int_eq(s21_strcmp(s1, s10), strcmp(s1, s10));

}
END_TEST

START_TEST(s21_strncmp_test)
{
char s1[20] = "Hello world\0";
char s2[15] = "Hello world\n\0";
char s3[20] = "a\n\0";
char s4[20] = " \n\0";
char s5[6] = " \0";
char s6[4] = "\n\0";
char s7[2] = "\0";
char s8[4] = "aaa";
char s9[2] = "";
    
ck_assert_int_eq(s21_strncmp(s1, s2, 11), strncmp(s1, s2, 11));
ck_assert_int_eq(s21_strncmp(s1, s2, 12), strncmp(s1, s2, 12));
ck_assert_int_eq(s21_strncmp(s4, s5, 1), strncmp(s4, s5, 1));
ck_assert_int_eq(s21_strncmp(s4, s5, 2), strncmp(s4, s5, 2));
ck_assert_int_eq(s21_strncmp(s5, s7, 1), strncmp(s5, s7, 1));
ck_assert_int_eq(s21_strncmp(s5, s7, 2), strncmp(s5, s7, 2));
ck_assert_int_eq(s21_strncmp(s3, s4, 2), strncmp(s3, s4, 2));
ck_assert_int_eq(s21_strncmp(s3, s4, 3), strncmp(s3, s4, 3));
ck_assert_int_eq(s21_strncmp(s6, s7, 1), strncmp(s6, s7, 1));
ck_assert_int_eq(s21_strncmp(s6, s7, 2), strncmp(s6, s7, 2));
ck_assert_int_eq(s21_strncmp(s8, s9, 3), strncmp(s8, s9, 3));

}
END_TEST

START_TEST(s21_strcpy_test)
{
char s1[20] = "Hello world\0";
char s2[15] = "Hello world\n\0";
char s3[20] = "a\n\0";
char s4[20] = " \n\0";
char s5[6] = " \0";
char s6[4] = "\n\0";
char s7[2] = "\0";
char s8[4] = "aaa";
char s9[2] = "D";
char s10[20] = "Hello world\0";
char s11[20] = "hello world";
char s12[8] = "Q";

ck_assert_str_eq(s21_strcpy(s11, s12), strcpy(s11, s12));
ck_assert_str_eq(s21_strcpy(s3, s4), strcpy(s3, s4));
ck_assert_str_eq(s21_strcpy(s1, s2), strcpy(s1, s2));
ck_assert_str_eq(s21_strcpy(s10, s8), strcpy(s10, s8));
ck_assert_str_eq(s21_strcpy(s5, s6), strcpy(s5, s6));
ck_assert_str_eq(s21_strcpy(s1, s10), strcpy(s1, s10));
ck_assert_str_eq(s21_strcpy(s5, s7), strcpy(s5, s7));
ck_assert_str_eq(s21_strcpy(s8, s9), strcpy(s8, s9));
ck_assert_str_eq(s21_strcpy(s6, s7), strcpy(s6, s7));

}
END_TEST

START_TEST(s21_strncpy_test)
{
char s1[20] = "Hello world\0";
char s2[15] = "Hello world\n\0";
char s3[20] = "a\n\0";
char s4[20] = " \n\0";
char s5[6] = " \0";
char s6[4] = "\n\0";
char s7[2] = "\0";
char s8[4] = "aaa";
char s9[2] = "D";
char s10[20] = "Hello world\0";
char s11[20] = "hello world";
char s12[8] = "Q";

ck_assert_str_eq(s21_strncpy(s11, s12, 2), strncpy(s11, s12, 2));
ck_assert_str_eq(s21_strncpy(s3, s4, 1), strncpy(s3, s4, 1));
ck_assert_str_eq(s21_strncpy(s1, s2, 3), strncpy(s1, s2, 3));
ck_assert_str_eq(s21_strncpy(s10, s8, 2), strncpy(s10, s8, 2));
ck_assert_str_eq(s21_strncpy(s5, s6, 1), strncpy(s5, s6, 1));
ck_assert_str_eq(s21_strncpy(s1, s9, 7), strncpy(s1, s9, 7));
ck_assert_str_eq(s21_strncpy(s5, s7, 1), strncpy(s5, s7, 1));
ck_assert_str_eq(s21_strncpy(s8, s9, 2), strncpy(s8, s9, 2));
ck_assert_str_eq(s21_strncpy(s6, s7, 1), strncpy(s6, s7, 1));

}
END_TEST

START_TEST(s21_strcspn_test)
{
char *test = "string for testing 123";
char *test2 = "231";
char *testNULL = s21_NULL;

ck_assert_int_eq(s21_strcspn(test, test2), strcspn(test, test2));
ck_assert_int_eq(s21_strcspn("123456789", "987"), strcspn("123456789", "987"));
ck_assert_int_eq(s21_strcspn("123456789", " "), strcspn("123456789", " "));
ck_assert_int_eq(s21_strcspn(" ", " "), strcspn(" ", " "));
ck_assert_int_eq(s21_strcspn("123456789", "\n"), strcspn("123456789", "\n"));
ck_assert_int_eq(s21_strcspn("123456789", testNULL), 0);

}
END_TEST

START_TEST(s21_strerror_test)
{
for (int i = 1; i <= MAX_ERROR; i++) {
        ck_assert_str_eq(s21_strerror(i), strerror(i));
    }

}
END_TEST

START_TEST(s21_strlen_test)
{
char *str = "Test string";
ck_assert_int_eq(s21_strlen(str), strlen(str));
ck_assert_int_eq(s21_strlen("55"), strlen("55"));
ck_assert_int_eq(s21_strlen(""), strlen(""));
ck_assert_int_eq(s21_strlen(" "), strlen(" "));
ck_assert_int_eq(s21_strlen("\n"), strlen("\n"));
ck_assert_int_eq(s21_strlen("How is\0this is a string"), strlen("How is\0this is a string"));

}
END_TEST

START_TEST(s21_strpbrk_test)
{
char *test = "string for testing 123";
char *test2 = "orf";
char *testNULL = s21_NULL;

ck_assert_str_eq(s21_strpbrk(test, test2), strpbrk(test, test2));
ck_assert_str_eq(s21_strpbrk("123456789", "9"), strpbrk("123456789", "9"));
ck_assert_msg(s21_strpbrk("123456789", "0") == s21_NULL, "s21_NULL should be returned s21_strbrk");
ck_assert_msg(s21_strpbrk("12345678", "09") == s21_NULL, "s21_NULL should be returned strbrk");
ck_assert_msg(s21_strpbrk(testNULL, "09") == s21_NULL, "s21_NULL should be returned strbrk");

}
END_TEST

START_TEST(s21_strrchr_test)
{
const char m1[] = "aetsghtaeghl";
int m2 = 'a';
ck_assert_ptr_eq(s21_strrchr(m1,m2), strrchr(m1,m2));

const char m3[] = "aetsghtaeghl";
int m4 = '2';
ck_assert_pstr_eq(s21_strrchr(m3, m4), strrchr(m3, m4));

const char m5[] = "";
int m6 = 'a';
ck_assert_pstr_eq(s21_strrchr(m5, m6), strrchr(m5, m6));

}
END_TEST

START_TEST(s21_strspn_test)
{
const char m7[] = "Hello world";
const char m8[] = "Hel";
ck_assert_int_eq(s21_strspn(m7, m8), strspn(m7, m8));
const char m9[] = "";
const char m10[] = "Hel";
ck_assert_int_eq(s21_strspn(m9, m10), strspn(m9, m10));
const char m11[] = "He\nllo world";
const char m12[] = "Hel";
ck_assert_int_eq(s21_strspn(m11, m12), strspn(m11, m12));
const char m13[] = "Hello world";
const char m14[] = "";
ck_assert_int_eq(s21_strspn(m13, m14), strspn(m13, m14));

}
END_TEST

START_TEST(s21_strstr_test)
{
const char m15[] = "abcdefcdw";
const char m16[] = "cd";
ck_assert_str_eq(s21_strstr(m15, m16), strstr(m15, m16));
const char m17[] = "abcefcdw";
const char m18[] = "cd";
ck_assert_pstr_eq(s21_strstr(m17, m18), strstr(m17, m18));
const char m19[] = "abcdefcdw";
const char m20[] = "kd";
ck_assert_pstr_eq(s21_strstr(m19, m20), strstr(m19, m20));
const char m21[] = "";
const char m22[] = "kd";
ck_assert_pstr_eq(s21_strstr(m21, m22), strstr(m21, m22));
const char m23[] = "abcde";
const char m24[] = "";
ck_assert_str_eq(s21_strstr(m23, m24), strstr(m23, m24));

}
END_TEST

START_TEST(s21_strtok_test)
{
char m25[] = "123_45,6";
const char m26[] = "_,";
ck_assert_ptr_eq(s21_strtok(m25, m26), strtok(m25, m26));
char m29[] = "";
const char m30[] = "_";
ck_assert_ptr_eq(s21_strtok(m29, m30), strtok(m29, m30));
char m31[] = "123_45";
const char m32[] = ",";
ck_assert_ptr_eq(s21_strtok(m31, m32), strtok(m31, m32));
char m33[] = "_123_45";
char m34[] = "_123_45";
const char m35[] = "_";
ck_assert_str_eq(s21_strtok(m33, m35), strtok(m34, m35));

}
END_TEST

START_TEST(s21_to_upper_test)
{
char *s1 = s21_to_upper("abcdef");
char *s2 = "ABCDEF";
char *s3 = s21_to_upper("aBcDeF");
char *s4 = "ABCDEF";
char *s5 = s21_to_upper("aBcDeF 123");
char *s6 = "ABCDEF 123";
char *s7 = s21_to_upper("");
char *s8 = "";
ck_assert_str_eq(s1, s2);
free(s1);
ck_assert_str_eq(s3, s4);
free(s3);
ck_assert_str_eq(s5, s6);
free(s5);
ck_assert_str_eq(s7, s8);
free(s7);

}
END_TEST

START_TEST(s21_to_lower_test)
{
char *s9 = s21_to_lower("ABCDEF");
char *s10 = "abcdef";
char *s11 = s21_to_lower("aBcDeF");
char *s12 = "abcdef";
char *s13 = s21_to_lower("aBcDeF 123");
char *s14 = "abcdef 123";
char *s15 = s21_to_lower("");
char *s16 = "";
ck_assert_str_eq(s9, s10);
free(s9);
ck_assert_str_eq(s11, s12);
free(s11);
ck_assert_str_eq(s13, s14);
free(s13);
ck_assert_str_eq(s15, s16);
free(s15);

}
END_TEST

START_TEST(s21_insert_test)
{
char *s17 = s21_insert("abcdef", "234", 5);
char *s18 = "abcde234f";
char *s19 = s21_insert("abcdef", "234", 0);
char *s20 = "234abcdef";
char *s21 = s21_insert("abcdef", "234", 6);
char *s22 = "abcdef234";
char *s23 = s21_insert("abcdef", "234", 28);
char *s24 = NULL;
char *s25 = s21_insert("abcdef", "", 3);
char *s26 = "abcdef";
char *s27 = s21_insert("", "234", 0);
char *s28 = "234";
ck_assert_str_eq(s17, s18);
free(s17);
ck_assert_str_eq(s19, s20);
free(s19);
ck_assert_str_eq(s21, s22);
free(s21);
ck_assert_pstr_eq(s23, s24);
free(s24);
ck_assert_str_eq(s25, s26);
free(s25);
ck_assert_str_eq(s27, s28);
free(s27);

}
END_TEST

START_TEST(s21_trim_test)
{
char *s29 = s21_trim("1211311abcdef11", "12");
char *s30 = "311abcdef";
char *s31 = s21_trim("812abcdef11", "12");
char *s32 = "812abcdef";
char *s33 = s21_trim("12abcdef11 ", "12");
char *s34 = "abcdef11 ";
char *s35 = s21_trim("", "12");
char *s36 = "";
char *s37 = s21_trim("abcdef", "");
char *s38 = "abcdef";
ck_assert_str_eq(s29, s30);
free(s29);
ck_assert_str_eq(s31, s32);
free(s31);
ck_assert_str_eq(s33, s34);
free(s33);
ck_assert_str_eq(s35, s36);
free(s35);
ck_assert_str_eq(s37, s38);
free(s37);

}
END_TEST

START_TEST(sprintf1)
{

char mas1[BUFFSIZE];
char mas2[BUFFSIZE];
char *format = "This is a simple value %d";
int val = 69;
ck_assert_int_eq(s21_sprintf(mas1, format, val),
                     sprintf(mas2, format, val));
ck_assert_str_eq(mas1, mas2);

}
END_TEST

START_TEST(sprintf2)
{
char mas3[BUFFSIZE];
char mas4[BUFFSIZE];

    char *format = "%.5i";
    int val = 69;
    ck_assert_int_eq(s21_sprintf(mas3, format, val),
                     sprintf(mas4, format, val));

    ck_assert_str_eq(mas3, mas4);

}
END_TEST

START_TEST(sprintf3)
{

char mas5[BUFFSIZE];
char mas6[BUFFSIZE];

    char *format = "%5d";
    int val = 69;
    ck_assert_int_eq(s21_sprintf(mas5, format, val),
                     sprintf(mas6, format, val));

    ck_assert_str_eq(mas5, mas6);

}
END_TEST

START_TEST(sprintf4)
{

char mas7[BUFFSIZE];
char mas8[BUFFSIZE];

    char *format = "%-5i";
    int val = 69;
    ck_assert_int_eq(s21_sprintf(mas7, format, val),
                     sprintf(mas8, format, val));

    ck_assert_str_eq(mas7, mas8);

}
END_TEST

START_TEST(sprintf5)
{

    char mas9[BUFFSIZE];
    char mas10[BUFFSIZE];

    char *format = "%+12d";
    int val = 69;
    ck_assert_int_eq(s21_sprintf(mas9, format, val),
                     sprintf(mas10, format, val));

    ck_assert_str_eq(mas9, mas10);

}
END_TEST

START_TEST(sprintf6)
{
    char mas11[BUFFSIZE];
    char mas12[BUFFSIZE];

    char *format = "%012i";
    int val = 69;
    ck_assert_int_eq(s21_sprintf(mas11, format, val),
                     sprintf(mas12, format, val));

    ck_assert_str_eq(mas11, mas12);

}
END_TEST

START_TEST(sprintf7)
{

    char mas13[BUFFSIZE];
    char mas14[BUFFSIZE];

    char *format = "%0*d";
    int val = 69;
    ck_assert_int_eq(s21_sprintf(mas13, format, 5, val),
                     sprintf(mas14, format, 5, val));

    ck_assert_str_eq(mas13, mas14);

}
END_TEST

START_TEST(sprintf8)
{
    char mas15[BUFFSIZE];
    char mas16[BUFFSIZE];

    char *format = "%0.*i";
    int val = 69;
    ck_assert_int_eq(s21_sprintf(mas15, format, 5, val),
                     sprintf(mas16, format, 5, val));

    ck_assert_str_eq(mas15, mas16);

}
END_TEST

START_TEST(sprintf9)
{
    char mas17[BUFFSIZE];
    char mas18[BUFFSIZE];

    char format[] = "%0.*i %d %4.*i %013d %d";
    int val = 69;
    ck_assert_int_eq(
        s21_sprintf(mas17, format, 5, val, -10431, 13, 5311, 0, -581813581),
        sprintf(mas18, format, 5, val, -10431, 13, 5311, 0, -581813581));

    ck_assert_str_eq(mas17, mas18);

}
END_TEST

START_TEST(sprintf10)
{
    char mas19[BUFFSIZE];
    char mas20[BUFFSIZE];

    char *format = "%+5.31li";
    long int val = 698518581899;
    ck_assert_int_eq(s21_sprintf(mas19, format, val),
                     sprintf(mas20, format, val));

    ck_assert_str_eq(mas19, mas20);

}
END_TEST

START_TEST(sprintf11)
{
    char mas21[BUFFSIZE];
    char mas22[BUFFSIZE];

    char *format = "%-16.9hi";
    short int val = 6958;
    ck_assert_int_eq(s21_sprintf(mas21, format, val),
                     sprintf(mas22, format, val));

    ck_assert_str_eq(mas21, mas22);

}
END_TEST

START_TEST(sprintf12)
{
    char mas23[BUFFSIZE];
    char mas24[BUFFSIZE];

    char *format = "%0.*ld";
    long val = 8581385185;
    ck_assert_int_eq(s21_sprintf(mas23, format, 5, val),
                     sprintf(mas24, format, 5, val));

    ck_assert_str_eq(mas23, mas24);

}
END_TEST

START_TEST(sprintf13)
{
    char mas25[BUFFSIZE];
    char mas26[BUFFSIZE];

    char *format = "%.0d";
    int val = 0;
    ck_assert_int_eq(s21_sprintf(mas25, format, val),
                     sprintf(mas26, format, val));

    ck_assert_str_eq(mas25, mas26);

}
END_TEST

START_TEST(sprintf14)
{
    char mas27[BUFFSIZE];
    char mas28[BUFFSIZE];

    char *format = "% d";
    int val = 0;
    ck_assert_int_eq(s21_sprintf(mas27, format, val),
                     sprintf(mas28, format, val));

    ck_assert_str_eq(mas27, mas28);

}
END_TEST

START_TEST(sprintf15)
{
    char mas29[BUFFSIZE];
    char mas30[BUFFSIZE];

    char *format = "%u";
    unsigned int val = 14140;
    ck_assert_int_eq(s21_sprintf(mas29, format, val),
                     sprintf(mas30, format, val));

    ck_assert_str_eq(mas29, mas30);

}
END_TEST

START_TEST(sprintf16)
{
    char mas31[BUFFSIZE];
    char mas32[BUFFSIZE];

    char *format = "%15u";
    unsigned int val = 14140;
    ck_assert_int_eq(s21_sprintf(mas31, format, val),
                     sprintf(mas32, format, val));

    ck_assert_str_eq(mas31, mas32);

}
END_TEST

START_TEST(sprintf17)
{
    char mas33[BUFFSIZE];
    char mas34[BUFFSIZE];

    char *format = "%-16u";
    unsigned int val = 14140;
    ck_assert_int_eq(s21_sprintf(mas33, format, val),
                     sprintf(mas34, format, val));

    ck_assert_str_eq(mas33, mas34);

}
END_TEST

START_TEST(sprintf18)
{
    char mas35[BUFFSIZE];
    char mas36[BUFFSIZE];

    char *format = "%.51u";
    unsigned int val = 14140;
    ck_assert_int_eq(s21_sprintf(mas35, format, val),
                     sprintf(mas36, format, val));

    ck_assert_str_eq(mas35, mas36);
}
END_TEST

START_TEST(sprintf19)
{
    char mas37[BUFFSIZE];
    char mas38[BUFFSIZE];

    char *format = "% 5.51u";
    unsigned int val = 14140;
    ck_assert_int_eq(s21_sprintf(mas37, format, val),
                     sprintf(mas38, format, val));

    ck_assert_str_eq(mas37, mas38);
}
END_TEST

START_TEST(sprintf20)
{
    char mas39[BUFFSIZE];
    char mas40[BUFFSIZE];

    char *format = "%hu";
    unsigned short int val = 14140;
    ck_assert_int_eq(s21_sprintf(mas39, format, val),
                     sprintf(mas40, format, val));

    ck_assert_str_eq(mas39, mas40);

}
END_TEST

START_TEST(sprintf21)
{
    char mas41[BUFFSIZE];
    char mas42[BUFFSIZE];

    char *format = "%u";
    unsigned long int val = 9114140;
    ck_assert_int_eq(s21_sprintf(mas41, format, val),
                     sprintf(mas42, format, val));

    ck_assert_str_eq(mas41, mas42);

}
END_TEST

START_TEST(sprintf22)
{
    char mas42[BUFFSIZE];
    char mas43[BUFFSIZE];

    char *format = "%u, %u, %hu, %.5u, %5.u";
    unsigned long int val = 9114140;
    ck_assert_int_eq(s21_sprintf(mas42, format, val, 14, 1441, 14414, 9681),
                     sprintf(mas43, format, val, (unsigned)14,
                             (unsigned short)1441, (unsigned)14414,
                             (unsigned)9681));

    ck_assert_str_eq(mas42, mas43);


}
END_TEST

START_TEST(sprintf23)
{

    char str70[BUFFSIZE];
    char str71[BUFFSIZE];

    char *format = "%c";
    char val = 'X';
    ck_assert_int_eq(s21_sprintf(str70, format, val),
                     sprintf(str71, format, val));

    ck_assert_str_eq(str70, str71);

}
END_TEST

START_TEST(sprintf24)
{

    char str72[BUFFSIZE];
    char str73[BUFFSIZE];

    char *format = "%.5c";
    char val = 'c';
    ck_assert_int_eq(s21_sprintf(str72, format, val),
                     sprintf(str73, format, val));

    ck_assert_str_eq(str72, str73);

}
END_TEST

START_TEST(sprintf25)
{


    char str74[BUFFSIZE];
    char str75[BUFFSIZE];

    char *format = "% -5c";
    char val = 'c';
    ck_assert_int_eq(s21_sprintf(str74, format, val),
                     sprintf(str75, format, val));

    ck_assert_str_eq(str74, str75);

}
END_TEST

START_TEST(sprintf26)
{

    char str76[BUFFSIZE];
    char str77[BUFFSIZE];

    char *format = "%15c";
    char val = 'c';
    ck_assert_int_eq(s21_sprintf(str76, format, val),
                     sprintf(str77, format, val));

    ck_assert_str_eq(str76, str77);

}
END_TEST

START_TEST(sprintf27)
{

    char str78[BUFFSIZE];
    char str79[BUFFSIZE];

    char *format = "%-5.3c%c%c%c%c Hello! ABOBA";
    char val = 'c';
    ck_assert_int_eq(s21_sprintf(str78, format, val, 'c', 'a', 'b', 'b'),
                     sprintf(str79, format, val, 'c', 'a', 'b', 'b'));

    ck_assert_str_eq(str78, str79);

}
END_TEST

START_TEST(sprintf28)
{

    char str80[BUFFSIZE];
    char str81[BUFFSIZE];

    char *format = "%-5.3c";
    char val = 'c';
    ck_assert_int_eq(s21_sprintf(str80, format, val),
                     sprintf(str81, format, val));

    ck_assert_str_eq(str80, str81);

}
END_TEST

START_TEST(sprintf29)
{

    char str82[BUFFSIZE];
    char str83[BUFFSIZE];

    char *format = "%-5.3c";
    char val = 'c';
    ck_assert_int_eq(s21_sprintf(str82, format, val),
                     sprintf(str83, format, val));

    ck_assert_str_eq(str82, str83);

}
END_TEST

START_TEST(sprintf30)
{

    char str84[BUFFSIZE];
    char str85[BUFFSIZE];

    char *format = "%s";
    char *val = "I LOVE STRINGS AND TESTS AND SCHOOL21 NO JOKE";
    ck_assert_int_eq(s21_sprintf(str84, format, val),
                     sprintf(str85, format, val));

    ck_assert_str_eq(str84, str85);

}
END_TEST

START_TEST(sprintf31)
{

    char str86[BUFFSIZE];
    char str87[BUFFSIZE];

    char *format = "%.15s";
    char *val = "I LOVE STRINGS AND TESTS AND SCHOOL21 NO JOKE";
    ck_assert_int_eq(s21_sprintf(str86, format, val),
                     sprintf(str87, format, val));

    ck_assert_str_eq(str86, str87);

}
END_TEST

START_TEST(sprintf32)
{

    char str88[BUFFSIZE];
    char str89[BUFFSIZE];

    char *format = "%15s";
    char *val = "69 IS MY FAVORITE NUMBER";
    ck_assert_int_eq(s21_sprintf(str88, format, val),
                     sprintf(str89, format, val));

    ck_assert_str_eq(str88, str89);


}
END_TEST

START_TEST(sprintf33)
{

    char str90[BUFFSIZE];
    char str91[BUFFSIZE];

    char *format = "%-15.9s";
    char *val = "69 IS MY FAVORITE NUMBER";
    ck_assert_int_eq(s21_sprintf(str90, format, val),
                     sprintf(str91, format, val));

    ck_assert_str_eq(str90, str91);


}
END_TEST

START_TEST(sprintf34)
{

    char str92[BUFFSIZE];
    char str93[BUFFSIZE];

    char *format = "%s";
    char *val =
        "69 IS MY FAVORITE NUMBER THIS IS SUPPOSED TO BE A VERY LONG STRING";
    ck_assert_int_eq(s21_sprintf(str92, format, val),
                     sprintf(str93, format, val));

    ck_assert_str_eq(str92, str93);


}
END_TEST

START_TEST(sprintf35)
{

    char str94[BUFFSIZE];
    char str95[BUFFSIZE];

    char *format = "%s%s%s%s";
    char *val =
        "69 IS MY FAVORITE NUMBER THIS IS SUPPOSED TO BE A VERY LONG STRING";
    char *s1 = "";
    char *s2 = "87418347813748913749871389480913";
    char *s3 = "HAHAABOBASUCKER";
    ck_assert_int_eq(s21_sprintf(str94, format, val, s1, s2, s3),
                     sprintf(str95, format, val, s1, s2, s3));

    ck_assert_str_eq(str94, str95);

}
END_TEST

START_TEST(sprintf36)
{

    char str96[BUFFSIZE];
    char str97[BUFFSIZE];
    char *val = "kjafdiuhfjahfjdahf";
    char *format = "%120s";
    ck_assert_int_eq(s21_sprintf(str96, format, val),
                     sprintf(str97, format, val));

    ck_assert_str_eq(str96, str97);

}
END_TEST

START_TEST(sprintf37)
{

    char str98[BUFFSIZE];
    char str99[BUFFSIZE];
    char *format = "%10f";
    long double val = 15.35;
    ck_assert_int_eq(s21_sprintf(str98, format, val),
                     sprintf(str99, format, val));

    ck_assert_str_eq(str98, str99);


}
END_TEST

START_TEST(sprintf38)
{

    char str100[BUFFSIZE];
    char str101[BUFFSIZE];
    char format[6] = "%.0f";
    long double val = 15.35;
    ck_assert_int_eq(s21_sprintf(str100, format, val),
                     sprintf(str101, format, val));

    ck_assert_str_eq(str100, str101);

}
END_TEST

START_TEST(sprintf39)
{

    char str102[BUFFSIZE];
    char str103[BUFFSIZE];
    char *format = "%.f";
    long double val = 15.35;
    ck_assert_int_eq(s21_sprintf(str102, format, val),
                     sprintf(str103, format, val));

    ck_assert_str_eq(str102, str103);


}
END_TEST

START_TEST(sprintf40)
{

    char str104[BUFFSIZE];
    char str105[BUFFSIZE];
    char *format = "%.15f";
    long double val = 15.35;
    ck_assert_int_eq(s21_sprintf(str104, format, val),
                     sprintf(str105, format, val));

    ck_assert_str_eq(str104, str105);

}
END_TEST

START_TEST(sprintf41)
{

    char str106[BUFFSIZE];
    char str107[BUFFSIZE];
    char *format = "%.15f";
    long double val = -15.35581134;
    ck_assert_int_eq(s21_sprintf(str106, format, val),
                     sprintf(str107, format, val));

    ck_assert_str_eq(str106, str107);

}
END_TEST

START_TEST(sprintf42)
{

    char str108[BUFFSIZE];
    char str109[BUFFSIZE];
    char *format = "%f";
    long double val = 72537572375.1431341;
    ck_assert_int_eq(s21_sprintf(str108, format, val),
                     sprintf(str109, format, val));

    ck_assert_str_eq(str108, str109);

}
END_TEST

START_TEST(sprintf43)
{

    char str1008[BUFFSIZE];
    char str1009[BUFFSIZE];
    char *format = "% f";
    float val = 0;
    ck_assert_int_eq(s21_sprintf(str1008, format, val),
                     sprintf(str1009, format, val));

    ck_assert_str_eq(str1008, str1009);


}
END_TEST

START_TEST(sprintf47)
{

    char str116[BUFFSIZE];
    char str117[BUFFSIZE];
    ck_assert_int_eq(s21_sprintf(str116, "%c%c%c%c%c", '\t', '\n', '0', 'S', 's'),
                     sprintf(str117, "%c%c%c%c%c", '\t', '\n', '0', 'S', 's'));

    ck_assert_str_eq(str116, str117);

}
END_TEST

START_TEST(sprintf48)
{

    char str118[BUFFSIZE];
    char str119[BUFFSIZE];

    ck_assert_int_eq(s21_sprintf(str118, "%s", "Drop Sega PLS"),
                     sprintf(str119, "%s", "Drop Sega PLS"));

    ck_assert_str_eq(str118, str119);


}
END_TEST

START_TEST(sprintf49)
{

    char str120[BUFFSIZE];
    char str121[BUFFSIZE];

    ck_assert_int_eq(
        s21_sprintf(str120, "%s%s%s%s%s", "Drop", " ", "Sega", " ", "PLS"),
        sprintf(str121, "%s%s%s%s%s", "Drop", " ", "Sega", " ", "PLS"));

    ck_assert_str_eq(str120, str121);

}
END_TEST

START_TEST(sprintf50)
{

    char str122[BUFFSIZE];
    char str123[BUFFSIZE];

    ck_assert_int_eq(s21_sprintf(str122, "%d", 666), sprintf(str123, "%d", 666));

    ck_assert_str_eq(str122, str123);


}
END_TEST

START_TEST(sprintf51)
{

    char str124[BUFFSIZE];
    char str125[BUFFSIZE];

    ck_assert_int_eq(s21_sprintf(str124, "%d%d%d%d", -999, 0, 666, -100),
                     sprintf(str125, "%d%d%d%d", -999, 0, 666, -100));

    ck_assert_str_eq(str124, str125);

}
END_TEST

START_TEST(sprintf52)
{

    char str126[BUFFSIZE];
    char str127[BUFFSIZE];

    ck_assert_int_eq(s21_sprintf(str126, "%i", -0), sprintf(str127, "%i", -0));

    ck_assert_str_eq(str126, str127);

}
END_TEST

START_TEST(sprintf53)
{

    char str128[BUFFSIZE];
    char str129[BUFFSIZE];

    ck_assert_int_eq(s21_sprintf(str128, "%i%i%i%i", -999, 0, 666, -100),
                     sprintf(str129, "%i%i%i%i", -999, 0, 666, -100));

    ck_assert_str_eq(str128, str129);

}
END_TEST

START_TEST(sprintf54)
{

    char str130[BUFFSIZE];
    char str131[BUFFSIZE];

    ck_assert_int_eq(s21_sprintf(str130, "%f", 0.0001),
                     sprintf(str131, "%f", 0.0001));

    ck_assert_str_eq(str130, str131);

}
END_TEST

START_TEST(sprintf56)
{

    char str134[BUFFSIZE];
    char str135[BUFFSIZE];

    ck_assert_int_eq(s21_sprintf(str134, "%u", 100),
                     sprintf(str135, "%u", (unsigned)100));

    ck_assert_str_eq(str134, str135);


}
END_TEST

START_TEST(sprintf57)
{

    char str136[BUFFSIZE];
    char str137[BUFFSIZE];

    ck_assert_int_eq(s21_sprintf(str136, "%u%u%u%u", 999, 0, 666, 100),
                     sprintf(str137, "%u%u%u%u", (unsigned)999, (unsigned)0,
                             (unsigned)666, (unsigned)100));

    ck_assert_str_eq(str136, str137);

}
END_TEST

START_TEST(sprintf58)
{

    char str138[BUFFSIZE];
    char str139[BUFFSIZE];

    ck_assert_int_eq(s21_sprintf(str138, "%8c", '\t'),
                     sprintf(str139, "%8c", '\t'));

    ck_assert_str_eq(str138, str139);


}
END_TEST

START_TEST(sprintf59)
{

    char str140[BUFFSIZE];
    char str141[BUFFSIZE];

    ck_assert_int_eq(s21_sprintf(str140, "%-8c", '\t'),
                     sprintf(str141, "%-8c", '\t'));

    ck_assert_str_eq(str140, str141);

}
END_TEST

START_TEST(sprintf60)
{

    char str142[BUFFSIZE];
    char str143[BUFFSIZE];

    ck_assert_int_eq(
        s21_sprintf(str142, "%3c%-11c%10c%-2c%c", '\t', '\n', '0', 'S', 's'),
        sprintf(str143, "%3c%-11c%10c%-2c%c", '\t', '\n', '0', 'S', 's'));

    ck_assert_str_eq(str142, str143);

}
END_TEST

START_TEST(sprintf61)
{

    char str144[BUFFSIZE];
    char str145[BUFFSIZE];
    char format[] = "%10ld";

    ck_assert_int_eq(s21_sprintf(str144, format, 1), sprintf(str145, format, 1));

    ck_assert_str_eq(str144, str145);

}
END_TEST

START_TEST(sprintf62)
{

    char str146[BUFFSIZE];
    char str147[BUFFSIZE];
    char format[] = "%1.1f";

    ck_assert_int_eq(s21_sprintf(str146, format, 1.1),
                     sprintf(str147, format, 1.1));

    ck_assert_str_eq(str146, str147);


}
END_TEST

START_TEST(sprintf63)
{

    char str148[BUFFSIZE];
    char str149[BUFFSIZE];
    char format[] = "%8.3c";

    ck_assert_int_eq(s21_sprintf(str148, format, 'a'),
                     sprintf(str149, format, 'a'));

    ck_assert_str_eq(str148, str149);


}
END_TEST

START_TEST(sprintf64)
{

    char str150[BUFFSIZE];
    char str151[BUFFSIZE];
    char format[] = "%+5.5d aboba";

    int val = 10000;
    int a = s21_sprintf(str150, format, val);
    int b = sprintf(str151, format, val);
    ck_assert_int_eq(a, b);

    ck_assert_str_eq(str150, str151);

}
END_TEST

START_TEST(sprintf65)
{

    char str152[BUFFSIZE];
    char str153[BUFFSIZE];
    char format[] = "%7.7f";

    ck_assert_int_eq(s21_sprintf(str152, format, 11.123456),
                     sprintf(str153, format, 11.123456));

    ck_assert_str_eq(str152, str153);

}
END_TEST

START_TEST(sprintf66)
{

    char str154[BUFFSIZE];
    char str155[BUFFSIZE];
    char format[] = "%7.4s";

    ck_assert_int_eq(s21_sprintf(str154, format, "aboba floppa"),
                     sprintf(str155, format, "aboba floppa"));

    ck_assert_str_eq(str154, str155);

}
END_TEST

START_TEST(sprintf67)
{

    char str156[BUFFSIZE];
    char str157[BUFFSIZE];
    char format[] = "%6.6u";

    ck_assert_int_eq(s21_sprintf(str156, format, 12341151),
                     sprintf(str157, format, 12341151));

    ck_assert_str_eq(str156, str157);

}
END_TEST

START_TEST(sprintf68)
{

    char str158[BUFFSIZE];
    char str159[BUFFSIZE];
    char format[] = "%li%ld%lu";

    ck_assert_int_eq(s21_sprintf(str158, format, 666666666666, 777, 111),
                     sprintf(str159, format, 666666666666, 777, 111));

    ck_assert_str_eq(str158, str159);

}
END_TEST

START_TEST(sprintf69)
{

    char str160[BUFFSIZE];
    char str161[BUFFSIZE];
    char format[] = "%li%ld%lu";

    ck_assert_int_eq(s21_sprintf(str160, format, 666666666666, 777, 111),
                     sprintf(str161, format, 666666666666, 777, 111));

    ck_assert_str_eq(str160, str161);

}
END_TEST

START_TEST(sprintf70)
{

    char str162[BUFFSIZE];
    char str163[BUFFSIZE];
    char format[] = "% s";

    ck_assert_int_eq(s21_sprintf(str162, format, "aboba likes floppa"),
                     sprintf(str163, format, "aboba likes floppa"));

    ck_assert_str_eq(str162, str163);

}
END_TEST

START_TEST(sprintf71)
{

    char str164[BUFFSIZE];
    char str165[BUFFSIZE];
    char format[] = "% s% c";

    ck_assert_int_eq(s21_sprintf(str164, format, "", 'f'),
                     sprintf(str165, format, "", 'f'));

    ck_assert_str_eq(str164, str165);


}
END_TEST

START_TEST(sprintf72)
{

    char str165[BUFFSIZE];
    char str166[BUFFSIZE];
    char *format = "%210s";

    ck_assert_int_eq(s21_sprintf(str165, format, "AHHAHAHA\0AHHAHAHAH"),
                     sprintf(str166, format, "AHHAHAHA\0AHHAHAHAH"));

    ck_assert_str_eq(str165, str166);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, memchr_test);
    tcase_add_test(tc1_1, memcmp_test);
    tcase_add_test(tc1_1, memcpy_test);
    tcase_add_test(tc1_1, memmove1);
    tcase_add_test(tc1_1, memset_test);
    tcase_add_test(tc1_1, strcat_test);
    tcase_add_test(tc1_1, strncat_test);
    tcase_add_test(tc1_1, strchr_test);
    tcase_add_test(tc1_1, s21_strcmp_test);
    tcase_add_test(tc1_1, s21_strncmp_test);
    tcase_add_test(tc1_1, s21_strcpy_test);
    tcase_add_test(tc1_1, s21_strncpy_test);
    tcase_add_test(tc1_1, s21_strcspn_test);
    tcase_add_test(tc1_1, s21_strerror_test);
    tcase_add_test(tc1_1, s21_strlen_test);
    tcase_add_test(tc1_1, s21_strpbrk_test);
    tcase_add_test(tc1_1, s21_strrchr_test);
    tcase_add_test(tc1_1, s21_strspn_test);
    tcase_add_test(tc1_1, s21_strstr_test);
    tcase_add_test(tc1_1, s21_strtok_test);
    tcase_add_test(tc1_1, s21_to_upper_test);
    tcase_add_test(tc1_1, s21_to_lower_test);
    tcase_add_test(tc1_1, s21_insert_test);
    tcase_add_test(tc1_1, s21_trim_test);
    tcase_add_test(tc1_1, sprintf1);
    tcase_add_test(tc1_1, sprintf2);
    tcase_add_test(tc1_1, sprintf3);
    tcase_add_test(tc1_1, sprintf4);
    tcase_add_test(tc1_1, sprintf5);
    tcase_add_test(tc1_1, sprintf6);
    tcase_add_test(tc1_1, sprintf7);
    tcase_add_test(tc1_1, sprintf8);
    tcase_add_test(tc1_1, sprintf9);
    tcase_add_test(tc1_1, sprintf10);
    tcase_add_test(tc1_1, sprintf11);
    tcase_add_test(tc1_1, sprintf12);
    tcase_add_test(tc1_1, sprintf13);
    tcase_add_test(tc1_1, sprintf14);
    tcase_add_test(tc1_1, sprintf15);
    tcase_add_test(tc1_1, sprintf16);
    tcase_add_test(tc1_1, sprintf17);
    tcase_add_test(tc1_1, sprintf18);
    tcase_add_test(tc1_1, sprintf19);
    tcase_add_test(tc1_1, sprintf20);
    tcase_add_test(tc1_1, sprintf21);
    tcase_add_test(tc1_1, sprintf22);
    tcase_add_test(tc1_1, sprintf23);
    tcase_add_test(tc1_1, sprintf24);
    tcase_add_test(tc1_1, sprintf25);
    tcase_add_test(tc1_1, sprintf26);
    tcase_add_test(tc1_1, sprintf27);
    tcase_add_test(tc1_1, sprintf28);
    tcase_add_test(tc1_1, sprintf29);
    tcase_add_test(tc1_1, sprintf30);
    tcase_add_test(tc1_1, sprintf31);
    tcase_add_test(tc1_1, sprintf32);
    tcase_add_test(tc1_1, sprintf33);
    tcase_add_test(tc1_1, sprintf34);
    tcase_add_test(tc1_1, sprintf35);
    tcase_add_test(tc1_1, sprintf36);
    tcase_add_test(tc1_1, sprintf37);
    tcase_add_test(tc1_1, sprintf38);
    tcase_add_test(tc1_1, sprintf39);
    tcase_add_test(tc1_1, sprintf40);
    tcase_add_test(tc1_1, sprintf41);
    tcase_add_test(tc1_1, sprintf42);
    tcase_add_test(tc1_1, sprintf43);
    tcase_add_test(tc1_1, sprintf47);
    tcase_add_test(tc1_1, sprintf48);
    tcase_add_test(tc1_1, sprintf49);
    tcase_add_test(tc1_1, sprintf50);
    tcase_add_test(tc1_1, sprintf51);
    tcase_add_test(tc1_1, sprintf52);
    tcase_add_test(tc1_1, sprintf53);
    tcase_add_test(tc1_1, sprintf54);
    tcase_add_test(tc1_1, sprintf56);
    tcase_add_test(tc1_1, sprintf57);
    tcase_add_test(tc1_1, sprintf58);
    tcase_add_test(tc1_1, sprintf59);
    tcase_add_test(tc1_1, sprintf60);
    tcase_add_test(tc1_1, sprintf61);
    tcase_add_test(tc1_1, sprintf62);
    tcase_add_test(tc1_1, sprintf63);
    tcase_add_test(tc1_1, sprintf64);
    tcase_add_test(tc1_1, sprintf65);
    tcase_add_test(tc1_1, sprintf66);
    tcase_add_test(tc1_1, sprintf67);
    tcase_add_test(tc1_1, sprintf68);
    tcase_add_test(tc1_1, sprintf69);
    tcase_add_test(tc1_1, sprintf70);
    tcase_add_test(tc1_1, sprintf71);
    tcase_add_test(tc1_1, sprintf72);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
